//all the languages deepL supports packaged as tuples, first element in tuple is the language's ISO 639-1 code

const ListOfLanguages = [
    ['AR', 'Arabic'],
    ['BG', 'Bulgarian'],
    ['CS', 'Czech'],
    ['DA', 'Danish'],
    ['DE', 'German'],
    ['EL', 'Greek'],
    ['EN-US', 'English'],
    ['ES', 'Spanish'],
    ['ET', 'Estonian'],
    ['FI', 'Finnish'],
    ['FR', 'French'],
    ['HU', 'Hungarian'],
    ['ID', 'Indonesian'],
    ['IT', 'Italian'],
    ['JA', 'Japanese'],
    ['KO', 'Korean'],
    ['LT', 'Lithuanian'],
    ['LV', 'Latvian'],
    ['NB', 'Norwegian'],
    ['NL', 'Dutch'],
    ['PL', 'Polish'],
    ['PT-PT', 'Portuguese'],
    ['RO', 'Romanian'],
    ['RU', 'Russian'],
    ['SK', 'Slovak'],
    ['SL', 'Slovenian'],
    ['SV', 'Swedish'],
    ['TR', 'Turkish'],
    ['UK', 'Ukrainian'],
    ['ZH', 'Chinese'],
];

export default ListOfLanguages;